### ISSUE TITLE
gcloud set project should be anti-pattern

### ISSUE THREAD

**Issue by qjhart** [ucd-library/cork-kube#1]
The gcloud wrapper includes a set project command https://github.com/ucd-library/cork-kube/blob/a9b44f7e75333ed750d9139f3f8a70c1f9ffc28a/lib/gcloud.js#L19

This can be problematic, especially for users that maintain configurations where those configurations are overwritten.

```bash
quinn@qjh:~/aggie-experts$ gcloud config configurations list
NAME           IS_ACTIVE  ACCOUNT             PROJECT        COMPUTE_DEFAULT_ZONE  COMPUTE_DEFAULT_REGION
aggie-experts  False      qjhart@ucdavis.edu  ucdlib-dams  us-west1-c            us-west1
```

Is it possible to use an environment variable to set that for the duration of the command.  Eg in aggie experts we require developers to have a specific configuration, but use a variable to set that for the command-line runs. 

https://github.com/ucd-library/aggie-experts/blob/952e3ab3f3c7441200519c7e51c19a3ce12425f4/bin/aggie-experts#L741

**Comment by qjhart** [comment]
@UcDust gets tripped up running `aggie-experts` builds eg.

**Comment by jrmerz** [comment]
Ensuring proper project and username is core functionality for `cork-kube` so `kubectl` is setup and can be used along side of `cork-kube`.  How about we lean into gcloud configurations, and have `cork-kube`:

- Create configurations for each project/env
- Set any/all gcloud defaults provided by the .cork-kube-config file to that configuration
- `cork-kube init` then simply activates the configuration

thougths?

**Comment by qjhart** [comment]
That seems reasonable to me, I like standardizing on those.  But set it with the environment variable and not the `gcloud config configurations activate` so that it doesn't change the users working setup. I don't know the environment your wrappers  run in, eg. https://github.com/ucd-library/cork-kube/blob/a9b44f7e75333ed750d9139f3f8a70c1f9ffc28a/lib/gcloud.js#L23 but for scripts `gcloud` will honor the 'CLOUDSDK_ACTIVE_CONFIG_NAME` so one plan could be that if that environment variable isn't set then set it to the appropriate project, but if it is set, then leave it be.

**Comment by jrmerz** [comment]
as of `@ucd-lib/cork-kube@0.5.0` all `kubectl` commands will leverage `--context` and depending on the command `--namespace` flag(s) to talk to the proper k8s cluster.  All `gcloud` commands will leverage the `--configuration` flag to use the proper project/zone for that project as well as ensure the account is correct.

To leverage `gcloud configurations`, `cork-kube` will now automatically create `gcloud configurations` for each project/environment using the name `[project-name]-[env-name]`.  If the k8s context is not available for the gke environment, it will be automatically activated via `gcloud` using the projects/env configuration.  However, after the `gcloud container clusters get-credentials` command is run for you, the k8s active context will be set back to whatever your current context was (get-credentials changes your context by default).

*IMPORTANT*

This means running commands will no longer automatically update your active context for `kubectl` or project/configuration for `gcloud`.  However, the `cork-kube activate` (formally `cork-kube init`, though an alias still exists) will update both cli's.  So if you are working on a project, this is a good command to run.  I might add it as part of the standard vscode startup.

If you are ever wondering what your various context/projects CLI's are configured to talk to `cork-kube status` will print a simplified picture for your.
